author: KingRat
description: Create a huge, flat world in a block of your choice!
main: me.kingrat.plugins.hugetractsofland.HugeTractsOfLand
name: HugeTractsOfLand
url: http://www.infected-gaming.co.uk/
version: '1.0'
